// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEPUSHXjD136xBx9TnWoDGHl215jJikK0',
    appId: '1:529098258214:web:b8bdbd7b0209fc708a73e7',
    messagingSenderId: '529098258214',
    projectId: 't-shop-cea12',
    authDomain: 't-shop-cea12.firebaseapp.com',
    storageBucket: 't-shop-cea12.firebasestorage.app',
    measurementId: 'G-1YHF21DX9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZX7cQ9C2cnHspNEUcT9q8CiUMeEOJM_Y',
    appId: '1:529098258214:android:b6ee0de15c4b4a198a73e7',
    messagingSenderId: '529098258214',
    projectId: 't-shop-cea12',
    storageBucket: 't-shop-cea12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvb2BGcYK_HbdJij8y-lmG1DKfoNhYH-Y',
    appId: '1:529098258214:ios:6ee38f6ddd7b81ff8a73e7',
    messagingSenderId: '529098258214',
    projectId: 't-shop-cea12',
    storageBucket: 't-shop-cea12.firebasestorage.app',
    iosBundleId: 'com.example.toyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvb2BGcYK_HbdJij8y-lmG1DKfoNhYH-Y',
    appId: '1:529098258214:ios:6ee38f6ddd7b81ff8a73e7',
    messagingSenderId: '529098258214',
    projectId: 't-shop-cea12',
    storageBucket: 't-shop-cea12.firebasestorage.app',
    iosBundleId: 'com.example.toyshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEPUSHXjD136xBx9TnWoDGHl215jJikK0',
    appId: '1:529098258214:web:6e4f793bc50cdc2b8a73e7',
    messagingSenderId: '529098258214',
    projectId: 't-shop-cea12',
    authDomain: 't-shop-cea12.firebaseapp.com',
    storageBucket: 't-shop-cea12.firebasestorage.app',
    measurementId: 'G-8WD7FBQX0Z',
  );
}
